site_name: Лабораторные работы
nav:
  - Введение: index.md
  # - ЛР № 1:
  #       - Выполнение: s2/lab1_s2/lab.md
  - ЛР № 1:
      - Выполнение: lab1/task1.md
  - ЛР № 2:
      - Выполнение: lab2/task.md
#   - ПР № 3:
#       - Выполнение: pr3/task.md
#   - ЛР № 3:
#       - Выполнение: lab3/task.md
#   - ЛР № 4:
#       - Выполнение: lab4/task.md
    